image: docker:19.03.0

stages:
- pre-build
- build
- test
- deploy
- notificacao

# build-docker:
#   services:
#     - docker:19.03.0-dind
#   retry: 2
#   before_script:
#     - docker info
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

#   stage: pre-build
#   script:
#     - docker build -t minha-imagem .
#     - docker tag minha-imagem jonilsonds9/minha-imagem:latest
#     - docker push jonilsonds9/minha-imagem:latest

# build-project:
#   image: jonilsonds9/minha-imagem:latest
#   services:
#     - docker:19.03.0-dind
#     - mysql:5.7
#   variables:
#     MYSQL_USER: $DB_USER
#     MYSQL_PASSWORD: $DB_PASSWORD
#     MYSQL_DATABASE: $DB_DATABASE
#     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD

#     DB_NAME: $DB_DATABASE
#     DB_USER: $DB_USER
#     DB_PASSWORD: $DB_PASSWORD
#     DB_PORT: '3306'
#     DB_HOST: 'mysql'
#     SECRET_KEY: $DB_SECRET_KEY
#   stage: build
#   tags:
#     - executor-tarefas
#   dependencies:
#     - build-docker
#   script:
#     - python manage.py makemigrations
#     - python manage.py migrate

# test-project:
#   image: jonilsonds9/minha-imagem:latest
#   stage: test
#   services:
#     - docker:19.03.0-dind
#     - mysql:5.7
#   variables:
#     MYSQL_USER: $DB_USER
#     MYSQL_PASSWORD: $DB_PASSWORD
#     MYSQL_DATABASE: $DB_DATABASE
#     MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD

#     DB_NAME: $DB_DATABASE
#     DB_USER: $DB_USER
#     DB_PASSWORD: $DB_PASSWORD
#     DB_PORT: '3306'
#     DB_HOST: 'mysql'
#     SECRET_KEY: $DB_SECRET_KEY
#   dependencies:
#     - build-project
#   tags:
#     - executor-tarefas
#   script:
#     - python -m unittest setUp

deploy-project:
  stage: deploy
  tags:
    - executor-deploy
  # dependencies:
  #   - test-project
  script:
    - tar cfz arquivos.tgz *
    - scp arquivos.tgz jonilson@192.168.1.3:/home/jonilson/alura/11-Gitlab-CI-e-Docker/deploys
    - ssh jonilson@192.168.1.3 'cd /home/jonilson/alura/11-Gitlab-CI-e-Docker/deploys/; tar xfz arquivos.tgz; docker-compose up -d'

notificacao-sucesso:
  stage: notificacao
  tags:
    - executor-deploy
  when: on_success
  script:
    - echo "tudo deu certo"

notificacao-falhas:
  stage: notificacao
  tags:
    - executor-deploy
  when: on_failure
  script:
    - echo "deu errado"